In [1]:
import pandas as pd
train = pd.read_csv('twitter_training.csv')

In [2]:
data = train.sample(10000,random_state=42)
train.shape

(74681, 4)

In [3]:
# data Explorations
train['Positive'].value_counts()

Positive
Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [12]:
data.head()

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [5]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    101
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(56)

In [7]:
# data Cleaning remove duplicate also
data = data.dropna()
data.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [8]:
data.drop_duplicates(inplace = True)

In [30]:
data.duplicated().sum()

np.int64(171)

In [10]:
data.head(5)

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [11]:
data.drop(columns = ['2401','Borderlands'],inplace = True)

In [12]:
data.head(5)

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [13]:
data.rename(columns = {'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweets'},inplace = True)

In [14]:
data.head()

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [15]:
data[(data['Sentiment'] == 'Positive') | (data['Sentiment'] == 'Negative') | (data['Sentiment'] == 'Neutral')]

      Sentiment                                             Tweets
21704  Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008  Negative  Pay attention executive administrators. While ...
454    Positive                                                one
58076  Negative       @Rainbow6Game Server are Available in Xbox 🥺
40659  Positive  so Awesome siege attempt... strangest bleeding...
...         ...                                                ...
5763    Neutral  @OtakuWeeb11 Thanks for entering Grand Summone...
6213   Positive        Couldn't agree some more. It'S s excellent.
12347  Negative  Soooo no token market update for the rest of t...
2515   Positive  For anyone jumping into this Beta weekend, I h...
57264   Neutral  Week 1. Perfection MTG.. ---------------------...

[8094 rows x 2 columns]

In [16]:
data.head()

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [17]:
data['Sentiment'].value_counts()

Sentiment
Negative      2982
Positive      2795
Neutral       2317
Irrelevant    1759
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Sentiment'] = le.fit_transform(data['Sentiment'])

In [19]:
data.head(5)

       Sentiment                                             Tweets
34877          0  went to go in george's room to find his door w...
21704          3         Yo this looks LIT! Team:GO/Overwatch combo
47008          1  Pay attention executive administrators. While ...
7969           0  Guy looked at me and says my name was put on t...
454            3                                                one

In [20]:
#Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data['Tweets'])
sequences = tokenizer.texts_to_sequences(data['Tweets'])

In [21]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'i': 3,
 'and': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'in': 8,
 'for': 9,
 'this': 10,
 'it': 11,
 'you': 12,
 'on': 13,
 'my': 14,
 'that': 15,
 'com': 16,
 'with': 17,
 'game': 18,
 'so': 19,
 'me': 20,
 'have': 21,
 'be': 22,
 'just': 23,
 'not': 24,
 'but': 25,
 'was': 26,
 'all': 27,
 'are': 28,
 'at': 29,
 'like': 30,
 'out': 31,
 'from': 32,
 '2': 33,
 'your': 34,
 'twitter': 35,
 'pic': 36,
 'as': 37,
 'get': 38,
 'now': 39,
 'we': 40,
 'they': 41,
 'if': 42,
 'good': 43,
 'has': 44,
 't': 45,
 'about': 46,
 'do': 47,
 'play': 48,
 'can': 49,
 'one': 50,
 'people': 51,
 'will': 52,
 'when': 53,
 'new': 54,
 'no': 55,
 'really': 56,
 'love': 57,
 'an': 58,
 "i'm": 59,
 'johnson': 60,
 'more': 61,
 'unk': 62,
 'time': 63,
 'up': 64,
 'some': 65,
 'by': 66,
 'what': 67,
 'see': 68,
 'shit': 69,
 '3': 70,
 'been': 71,
 'how': 72,
 'best': 73,
 'why': 74,
 '’': 75,
 'co': 76,
 'still': 77,
 "it's": 78,
 'or': 79,
 'facebook': 80,
 'who': 81,
 'great': 82,
 'https': 83,
 'got': 84,
 'games': 85,
 'because': 86,
 'even': 87,
 'go': 88,
 '1': 89,
 'playing': 90,
 'fucking': 91,
 'amazon': 92,
 'microsoft': 93,
 'xbox': 94,
 '4': 95,
 'dead': 96,
 'them': 97,
 'had': 98,
 'there': 99,
 'us': 100,
 'fuck': 101,
 'back': 102,
 's': 103,
 'only': 104,
 'rhandlerr': 105,
 '5': 106,
 'much': 107,
 'verizon': 108,
 'please': 109,
 'google': 110,
 'red': 111,
 'would': 112,
 'player': 113,
 'day': 114,
 'our': 115,
 "can't": 116,
 'going': 117,
 'tv': 118,
 'after': 119,
 'their': 120,
 'pubg': 121,
 'he': 122,
 'am': 123,
 'fifa': 124,
 'these': 125,
 'its': 126,
 'first': 127,
 'home': 128,
 'very': 129,
 'fun': 130,
 'over': 131,
 'today': 132,
 'most': 133,
 'gta': 134,
 'borderlands': 135,
 'battlefield': 136,
 'make': 137,
 'than': 138,
 'here': 139,
 '…': 140,
 'also': 141,
 'again': 142,
 'twitch': 143,
 'nvidia': 144,
 'ban': 145,
 'never': 146,
 'fix': 147,
 '2020': 148,
 'overwatch': 149,
 'wait': 150,
 "don't": 151,
 'thanks': 152,
 'bad': 153,
 'know': 154,
 'thank': 155,
 'want': 156,
 'call': 157,
 'then': 158,
 'think': 159,
 'video': 160,
 'amazing': 161,
 'last': 162,
 'eamaddennfl': 163,
 'damn': 164,
 'every': 165,
 'work': 166,
 'getting': 167,
 'i’m': 168,
 'ever': 169,
 'too': 170,
 'year': 171,
 'played': 172,
 'happy': 173,
 'say': 174,
 'his': 175,
 'redemption': 176,
 'watch': 177,
 'series': 178,
 'nba2k': 179,
 'well': 180,
 'fortnite': 181,
 "i've": 182,
 'v': 183,
 'into': 184,
 'news': 185,
 'world': 186,
 'u': 187,
 'x': 188,
 'any': 189,
 'ps5': 190,
 'team': 191,
 'rainbow6game': 192,
 'legends': 193,
 'man': 194,
 'live': 195,
 'league': 196,
 '10': 197,
 'players': 198,
 'another': 199,
 'being': 200,
 'big': 201,
 'did': 202,
 'ass': 203,
 'always': 204,
 'right': 205,
 'while': 206,
 'guys': 207,
 'off': 208,
 'help': 209,
 'need': 210,
 'youtu': 211,
 'next': 212,
 'win': 213,
 'depot': 214,
 'everyone': 215,
 'youtube': 216,
 'duty': 217,
 'black': 218,
 'looks': 219,
 'money': 220,
 'years': 221,
 'health': 222,
 'made': 223,
 'many': 224,
 'take': 225,
 'something': 226,
 'should': 227,
 'creed': 228,
 'look': 229,
 'come': 230,
 'way': 231,
 'already': 232,
 'actually': 233,
 'update': 234,
 'warcraft': 235,
 'down': 236,
 'such': 237,
 'other': 238,
 'thing': 239,
 'could': 240,
 'which': 241,
 'support': 242,
 'care': 243,
 'store': 244,
 'free': 245,
 'finally': 246,
 'her': 247,
 'pc': 248,
 'oh': 249,
 'stream': 250,
 'it’s': 251,
 'stop': 252,
 'via': 253,
 'better': 254,
 '100': 255,
 'him': 256,
 'were': 257,
 'before': 258,
 'hearthstone': 259,
 'csgo': 260,
 'access': 261,
 'nice': 262,
 'since': 263,
 'awesome': 264,
 '20': 265,
 'same': 266,
 'ghostrecon': 267,
 'online': 268,
 'done': 269,
 'buy': 270,
 'wtf': 271,
 'cool': 272,
 'give': 273,
 'hate': 274,
 'looking': 275,
 'excited': 276,
 'ly': 277,
 'life': 278,
 'lot': 279,
 'playstation': 280,
 'someone': 281,
 'keep': 282,
 'top': 283,
 'bit': 284,
 'wow': 285,
 '6': 286,
 'days': 287,
 'old': 288,
 'night': 289,
 'long': 290,
 'check': 291,
 'account': 292,
 'lol': 293,
 'start': 294,
 'gonna': 295,
 'playapex': 296,
 'having': 297,
 'doing': 298,
 'everything': 299,
 'pretty': 300,
 'super': 301,
 'mobile': 302,
 'ubisoft': 303,
 'feel': 304,
 'real': 305,
 'card': 306,
 'working': 307,
 'trying': 308,
 'use': 309,
 'where': 310,
 'god': 311,
 'baby': 312,
 'season': 313,
 'through': 314,
 'probably': 315,
 'war': 316,
 'nothing': 317,
 'hey': 318,
 'things': 319,
 'dota': 320,
 '7': 321,
 'm': 322,
 'absolutely': 323,
 'guy': 324,
 'im': 325,
 'those': 326,
 'cyberpunk': 327,
 'little': 328,
 'two': 329,
 'phone': 330,
 'both': 331,
 'making': 332,
 'does': 333,
 'details': 334,
 'can’t': 335,
 'times': 336,
 'hell': 337,
 'makes': 338,
 'tell': 339,
 'hope': 340,
 "doesn't": 341,
 'stupid': 342,
 'friends': 343,
 'against': 344,
 'miss': 345,
 "that's": 346,
 'let': 347,
 'find': 348,
 'without': 349,
 'almost': 350,
 'said': 351,
 'gaming': 352,
 'open': 353,
 'show': 354,
 'favorite': 355,
 'week': 356,
 'company': 357,
 'hard': 358,
 'anyone': 359,
 'service': 360,
 'yet': 361,
 'literally': 362,
 'pay': 363,
 'dont': 364,
 'uk': 365,
 'own': 366,
 'ea': 367,
 'sure': 368,
 'worst': 369,
 'powder': 370,
 'problem': 371,
 'tonight': 372,
 'until': 373,
 'try': 374,
 'coming': 375,
 'fact': 376,
 'part': 377,
 'stuff': 378,
 '2077': 379,
 'lost': 380,
 'won': 381,
 'hours': 382,
 'cant': 383,
 'servers': 384,
 'full': 385,
 'story': 386,
 'minutes': 387,
 'whole': 388,
 'banned': 389,
 'bf4db': 390,
 'cs': 391,
 '0': 392,
 'chance': 393,
 'release': 394,
 'app': 395,
 'gets': 396,
 'apex': 397,
 'tt': 398,
 'using': 399,
 'few': 400,
 'd': 401,
 "you're": 402,
 'far': 403,
 'sorry': 404,
 'went': 405,
 'pro': 406,
 'million': 407,
 'beautiful': 408,
 'trash': 409,
 'she': 410,
 'sad': 411,
 'used': 412,
 'assassins': 413,
 '19': 414,
 'business': 415,
 'crazy': 416,
 'y’all': 417,
 'end': 418,
 'away': 419,
 'thought': 420,
 'put': 421,
 'console': 422,
 'cold': 423,
 'around': 424,
 'community': 425,
 'vaccine': 426,
 'soon': 427,
 'idea': 428,
 'says': 429,
 '21': 430,
 'though': 431,
 'enjoy': 432,
 "didn't": 433,
 'hit': 434,
 'dota2': 435,
 'gameplay': 436,
 'enough': 437,
 'callofduty': 438,
 'second': 439,
 'interesting': 440,
 'ift': 441,
 'anything': 442,
 'watching': 443,
 'forward': 444,
 'perfect': 445,
 'line': 446,
 '2k': 447,
 'definitely': 448,
 'ops': 449,
 '”': 450,
 'kill': 451,
 'content': 452,
 'share': 453,
 'currently': 454,
 "i'll": 455,
 'mode': 456,
 '30': 457,
 'due': 458,
 'wrong': 459,
 'wanted': 460,
 'price': 461,
 "y'all": 462,
 'grand': 463,
 'ranked': 464,
 'during': 465,
 'took': 466,
 'screen': 467,
 'maybe': 468,
 'occurred': 469,
 'covid': 470,
 'change': 471,
 'ago': 472,
 'instead': 473,
 "assassin's": 474,
 'person': 475,
 'mean': 476,
 'huge': 477,
 'order': 478,
 'tried': 479,
 'reason': 480,
 'post': 481,
 'able': 482,
 'job': 483,
 'may': 484,
 'beluba': 485,
 'girl': 486,
 'read': 487,
 'else': 488,
 'w': 489,
 'level': 490,
 'weekend': 491,
 'system': 492,
 'don’t': 493,
 'shot': 494,
 'bought': 495,
 '12': 496,
 'madden': 497,
 'month': 498,
 'single': 499,
 'came': 500,
 '8': 501,
 'bro': 502,
 'fan': 503,
 '15': 504,
 'might': 505,
 'music': 506,
 'exciting': 507,
 'services': 508,
 'funny': 509,
 'friend': 510,
 'worth': 511,
 'epic': 512,
 'morning': 513,
 'latest': 514,
 'p': 515,
 'high': 516,
 'ps4': 517,
 'despite': 518,
 'customer': 519,
 'character': 520,
 'data': 521,
 'apps': 522,
 'warzone': 523,
 'die': 524,
 'internet': 525,
 'skin': 526,
 'face': 527,
 'talc': 528,
 'half': 529,
 'power': 530,
 'yo': 531,
 'list': 532,
 'graphics': 533,
 'gen': 534,
 'luck': 535,
 'broken': 536,
 'match': 537,
 'guess': 538,
 'based': 539,
 'e': 540,
 'taken': 541,
 'saying': 542,
 'killed': 543,
 'seeing': 544,
 'tomorrow': 545,
 'i’ve': 546,
 'set': 547,
 'name': 548,
 'playhearthstone': 549,
 'windows': 550,
 'net': 551,
 'together': 552,
 'point': 553,
 "won't": 554,
 'server': 555,
 'ok': 556,
 'seems': 557,
 'event': 558,
 'r': 559,
 'started': 560,
 'problems': 561,
 'run': 562,
 'finished': 563,
 'must': 564,
 'join': 565,
 'eu': 566,
 'believe': 567,
 'living': 568,
 'below': 569,
 'design': 570,
 'found': 571,
 'selling': 572,
 'feels': 573,
 'later': 574,
 'comes': 575,
 "haven't": 576,
 'rewards': 577,
 'pre': 578,
 'terrible': 579,
 'teams': 580,
 'called': 581,
 'annoying': 582,
 'suck': 583,
 'n2k': 584,
 'major': 585,
 'follow': 586,
 'proud': 587,
 'org': 588,
 'seriously': 589,
 'wanna': 590,
 'seen': 591,
 'hear': 592,
 'cards': 593,
 'yes': 594,
 'three': 595,
 'updates': 596,
 'months': 597,
 'myteam': 598,
 'drop': 599,
 'needs': 600,
 'loved': 601,
 'cause': 602,
 'yall': 603,
 'don': 604,
 'different': 605,
 '“': 606,
 'gone': 607,
 'boy': 608,
 'mad': 609,
 'holy': 610,
 'myself': 611,
 'homedepot': 612,
 'least': 613,
 'ur': 614,
 'blizzard': 615,
 'truly': 616,
 'sometimes': 617,
 'hour': 618,
 'welcome': 619,
 'talk': 620,
 've': 621,
 'under': 622,
 'completely': 623,
 'sound': 624,
 'hello': 625,
 'worse': 626,
 'family': 627,
 'ronnie2k': 628,
 'leave': 629,
 'experience': 630,
 'streaming': 631,
 'id': 632,
 'anymore': 633,
 'ready': 634,
 'pass': 635,
 'honestly': 636,
 'y': 637,
 'trailer': 638,
 'movie': 639,
 'review': 640,
 'smh': 641,
 'leagueoflegends': 642,
 'kinda': 643,
 'book': 644,
 'late': 645,
 'bring': 646,
 'tech': 647,
 'bitch': 648,
 'once': 649,
 'remember': 650,
 'iphone': 651,
 'sick': 652,
 'early': 653,
 'breakpoint': 654,
 'congratulations': 655,
 're': 656,
 '9': 657,
 'social': 658,
 'instagram': 659,
 'add': 660,
 'taking': 661,
 'stay': 662,
 'step': 663,
 'cod': 664,
 'yeah': 665,
 'totally': 666,
 'market': 667,
 'gold': 668,
 'c': 669,
 'complete': 670,
 'lmao': 671,
 'edition': 672,
 'death': 673,
 'n': 674,
 'products': 675,
 'trump': 676,
 'daily': 677,
 'city': 678,
 'patch': 679,
 'sucks': 680,
 'dlvr': 681,
 'place': 682,
 'keeps': 683,
 'special': 684,
 'link': 685,
 'kind': 686,
 'fans': 687,
 'yesterday': 688,
 'birthday': 689,
 'understand': 690,
 'gift': 691,
 'hot': 692,
 'saw': 693,
 'apple': 694,
 'joke': 695,
 'cute': 696,
 'kids': 697,
 'head': 698,
 'running': 699,
 'true': 700,
 'incredible': 701,
 'wins': 702,
 'left': 703,
 'each': 704,
 'omg': 705,
 'channel': 706,
 'mind': 707,
 'code': 708,
 'quite': 709,
 'launch': 710,
 'ghost': 711,
 'continue': 712,
 'battle': 713,
 'achievement': 714,
 'kills': 715,
 '3080': 716,
 'class': 717,
 'cannot': 718,
 'crap': 719,
 'wish': 720,
 'videos': 721,
 'decision': 722,
 'nba': 723,
 'number': 724,
 'issues': 725,
 'means': 726,
 "let's": 727,
 'bugs': 728,
 'moment': 729,
 "they're": 730,
 'switch': 731,
 'error': 732,
 'white': 733,
 'that’s': 734,
 'fps': 735,
 'waiting': 736,
 'garbage': 737,
 'rtx': 738,
 'thinking': 739,
 'playoverwatch': 740,
 'hi': 741,
 '•': 742,
 'dude': 743,
 'trust': 744,
 'released': 745,
 '11': 746,
 'global': 747,
 "what's": 748,
 'drive': 749,
 'word': 750,
 'canada': 751,
 'sold': 752,
 'small': 753,
 'beta': 754,
 'especially': 755,
 'weeks': 756,
 'told': 757,
 'takes': 758,
 'past': 759,
 'move': 760,
 'chinese': 761,
 'india': 762,
 'house': 763,
 'tho': 764,
 'worked': 765,
 'art': 766,
 'insane': 767,
 'poverty': 768,
 'warfare': 769,
 'police': 770,
 'gotta': 771,
 'article': 772,
 'paid': 773,
 'died': 774,
 'knows': 775,
 'steam': 776,
 'enjoyed': 777,
 'technology': 778,
 'easy': 779,
 'glad': 780,
 'box': 781,
 'received': 782,
 'buying': 783,
 'toxic': 784,
 'tired': 785,
 'f': 786,
 'plz': 787,
 'page': 788,
 'en': 789,
 'retweet': 790,
 'commission': 791,
 'original': 792,
 'l': 793,
 'main': 794,
 'b': 795,
 'absolute': 796,
 'listen': 797,
 'car': 798,
 'winning': 799,
 'okay': 800,
 'action': 801,
 'moments': 802,
 'decided': 803,
 "we're": 804,
 'turn': 805,
 "there's": 806,
 'group': 807,
 'works': 808,
 'bullshit': 809,
 'forever': 810,
 'spent': 811,
 'valorant': 812,
 'rt': 813,
 'safe': 814,
 'easports': 815,
 'bug': 816,
 'issue': 817,
 'coronavirus': 818,
 'short': 819,
 'sell': 820,
 'women': 821,
 'men': 822,
 'sense': 823,
 '14': 824,
 'earned': 825,
 'fire': 826,
 'rest': 827,
 'points': 828,
 'less': 829,
 'shooting': 830,
 'users': 831,
 'wild': 832,
 'either': 833,
 'version': 834,
 'developers': 835,
 'modern': 836,
 'search': 837,
 'behind': 838,
 'favourite': 839,
 '–': 840,
 'dope': 841,
 'powerful': 842,
 'fast': 843,
 'lose': 844,
 'history': 845,
 'government': 846,
 'added': 847,
 'talking': 848,
 'plays': 849,
 'deal': 850,
 'weird': 851,
 'slow': 852,
 'plan': 853,
 'report': 854,
 'biggest': 855,
 'email': 856,
 'state': 857,
 'school': 858,
 'ridiculous': 859,
 'hyped': 860,
 'lots': 861,
 'yourself': 862,
 'calling': 863,
 'theft': 864,
 '13': 865,
 'greatest': 866,
 'including': 867,
 'close': 868,
 'sea': 869,
 'ai': 870,
 'companies': 871,
 'o': 872,
 'esports': 873,
 'dear': 874,
 'fortnitegame': 875,
 'disappointed': 876,
 'couple': 877,
 'media': 878,
 'happened': 879,
 'sales': 880,
 'future': 881,
 'pls': 882,
 '000': 883,
 'digital': 884,
 'cuz': 885,
 'star': 886,
 'edge': 887,
 'site': 888,
 'gg': 889,
 'longer': 890,
 'goes': 891,
 'performance': 892,
 'feeling': 893,
 'enjoying': 894,
 'tournament': 895,
 'stuck': 896,
 'giving': 897,
 'af': 898,
 'item': 899,
 'hold': 900,
 'random': 901,
 'sony': 902,
 'rockstargames': 903,
 'break': 904,
 'final': 905,
 'connection': 906,
 'indian': 907,
 'heart': 908,
 'hero': 909,
 'racist': 910,
 'current': 911,
 'entire': 912,
 'stock': 913,
 'option': 914,
 'dark': 915,
 'ubisoftsupport': 916,
 'franchise': 917,
 "she's": 918,
 'pandemic': 919,
 'fall': 920,
 '16': 921,
 "isn't": 922,
 'quick': 923,
 'website': 924,
 'redeeming': 925,
 'delayed': 926,
 'turned': 927,
 'dumb': 928,
 'test': 929,
 'poor': 930,
 'spend': 931,
 'auto': 932,
 'heard': 933,
 'fake': 934,
 '60': 935,
 'football': 936,
 'summoners': 937,
 'golden': 938,
 'unit': 939,
 'ya': 940,
 '2016': 941,
 'beyond': 942,
 'sounds': 943,
 'shut': 944,
 'date': 945,
 'learning': 946,
 'tweet': 947,
 'result': 948,
 'matter': 949,
 'k': 950,
 'gamer': 951,
 'cry': 952,
 'anywhere': 953,
 'actual': 954,
 '09': 955,
 'plus': 956,
 'fight': 957,
 '18': 958,
 'ask': 959,
 'bc': 960,
 'halo': 961,
 'felt': 962,
 'cancer': 963,
 'quit': 964,
 'alone': 965,
 'log': 966,
 'tch': 967,
 'realize': 968,
 'shoot': 969,
 'brand': 970,
 'voice': 971,
 'fantastic': 972,
 'selected': 973,
 'side': 974,
 '70': 975,
 'boring': 976,
 'chat': 977,
 'excellent': 978,
 'human': 979,
 'nfl': 980,
 'dog': 981,
 'lets': 982,
 'created': 983,
 'demon': 984,
 'shitty': 985,
 'low': 986,
 'case': 987,
 'ahead': 988,
 'shows': 989,
 'extremely': 990,
 'ball': 991,
 'wikipedia': 992,
 'control': 993,
 'lately': 994,
 'song': 995,
 'mixer': 996,
 'zero': 997,
 'watched': 998,
 'squad': 999,
 'recently': 1000,
 ...}

In [22]:
tokenizer.word_counts

OrderedDict([('went', 65),
             ('to', 3916),
             ('go', 299),
             ('in', 2135),
             ("george's", 2),
             ('room', 16),
             ('find', 77),
             ('his', 168),
             ('door', 9),
             ('was', 782),
             ('locked', 7),
             ('climbed', 2),
             ('up', 408),
             ('side', 22),
             ('of', 2654),
             ('house', 30),
             ('look', 129),
             ('through', 88),
             ('window', 3),
             ('expecting', 3),
             ('see', 370),
             ('a', 3301),
             ('regrettable', 2),
             ('girl', 53),
             ('or', 343),
             ('something', 131),
             ('but', 800),
             ('no', 432),
             ('he', 227),
             ('playing', 296),
             ('fortnite', 164),
             ('yo', 48),
             ('this', 1948),
             ('looks', 136),
             ('lit', 15),
             ('team', 156),
             ('overwatch', 196),
             ('combo', 8),
             ('pay', 74),
             ('attention', 8),
             ('executive', 4),
             ('administrators', 3),
             ('while', 146),
             ('your', 579),
             ('stores', 19),
             ('are', 779),
             ('taking', 36),
             ('delivery', 16),
             ('orders', 15),
             ('for', 2121),
             ('pallets', 2),
             ('bricks', 2),
             ('downtown', 2),
             ('then', 187),
             ('you', 1670),
             ('were', 116),
             ('being', 150),
             ('used', 64),
             ('helping', 19),
             ('the', 5947),
             ('destruction', 6),
             ('private', 11),
             ('property', 8),
             ('guy', 85),
             ('looked', 18),
             ('at', 661),
             ('me', 951),
             ('and', 3582),
             ('says', 61),
             ('my', 1583),
             ('name', 46),
             ('put', 62),
             ('on', 1621),
             ('throw', 19),
             ('list', 48),
             ('lmaoooo', 2),
             ('get', 546),
             ('fuck', 265),
             ('watch', 166),
             ('weird', 26),
             ('ass', 149),
             ('dude', 31),
             ('one', 453),
             ('rainbow6game', 155),
             ('server', 45),
             ('available', 17),
             ('xbox', 286),
             ('🥺', 8),
             ('ban', 201),
             ('battlefield', 212),
             ('4', 283),
             ('player', 241),
             ('lilcoldlli', 2),
             ('has', 497),
             ('occurred', 55),
             ('details', 80),
             ('bf4db', 69),
             ('com', 1334),
             ('100…', 4),
             ('lmao', 35),
             ('gason', 1),
             ('might', 51),
             ('kill', 57),
             ('pls', 25),
             ('google', 247),
             ('definitions', 2),
             ('words', 9),
             ('before', 116),
             ('using', 67),
             ('them', 273),
             ('its', 224),
             ('mistake', 14),
             ('we', 533),
             ('have', 942),
             ('all', 780),
             ('made', 132),
             ('im', 85),
             ('getting', 174),
             ('secondhand', 2),
             ('embarrassment', 2),
             ('after', 231),
             ('cops', 10),
             ('ran', 15),
             ('crowd', 5),
             ('peaceful', 4),
             ('protesters', 3),
             ('over', 216),
             ('i’m', 174),
             ('blind', 6),
             ('i', 3868),
             ('can’t', 79),
             ('shit', 369),
             ('so', 1002),
             ('awesome', 114),
             ('siege', 21),
             ('attempt', 6),
             ('strangest', 3),
             ('bleeding', 4),
             ('out', 623),
             ('spinning', 7),
             ('sequence', 2),
             ('ever', 174),
             ('s', 261),
             ('first', 224),
             ('squadmate', 1),
             ('john', 10),
             ('could', 124),
             ('exactly', 18),
             ('which', 123),
             ("i'm", 417),
             ('really', 432),
             ('looking', 104),
             ('forward', 58),
             ('game', 1111),
             ('verizon', 252),
             ('sheds', 1),
             ('81', 3),
             ('000', 25),
             ('digital', 25),
             ('tv', 234),
             ('black', 137),
             ('cutting', 6),
             ('escalates', 1),
             ('breitbart', 2),
             ('entertainment', 10),
             ('internet', 49),
             ('gave', 18),
             ('way', 128),
             ('coke', 1),
             ('show', 75),
             ('money', 136),
             ('keep', 100),
             ('ch', 2),
             ('tmmobile', 1),
             ('guys', 146),
             ('very', 218),
             ('slow', 26),
             ('town', 10),
             ('tuba', 1),
             ('fix', 200),
             ('fucking', 294),
             ('pro', 65),
             ('am', 226),
             ('games', 310),
             ('2ksupport', 16),
             ('love', 423),
             ('how', 361),
             ('gives', 21),
             ('each', 33),
             ('new', 437),
             ('loot', 17),
             ('box', 29),
             ('support', 123),
             ('forgot', 19),
             ('when', 438),
             ('hated', 5),
             ('who', 322),
             ('mad', 40),
             ('about', 471),
             ('dame', 9),
             ('itself', 13),
             ('regular', 7),
             ('cover', 13),
             ('like', 634),
             ('kobe', 7),
             ('legend', 19),
             ('edition', 35),
             ('unk', 413),
             ('disrespect', 7),
             ('y’all', 63),
             ('showed', 15),
             ('wild', 27),
             ('simpletons', 1),
             ('only', 261),
             ('lol', 96),
             ("here's", 17),
             ('montage', 17),
             ('rescuing', 1),
             ('teammate', 10),
             ('spreadlovehxly', 2),
             ('few', 66),
             ('times', 79),
             ('other', 125),
             ('day', 238),
             ('they', 514),
             ('will', 441),
             ('forever', 28),
             ('be', 930),
             ('heart', 24),
             ('do', 469),
             ('kinda', 37),
             ('tho', 30),
             ('5', 254),
             ('friends', 78),
             ('players', 152),
             ('pokemon', 10),
             ('borderlands', 213),
             ('p', 50),
             ('much', 253),
             ('sims', 2),
             ('6', 99),
             ("haven't", 43),
             ('played', 171),
             ('spiderman', 2),
             ('2', 580),
             ('reignited', 1),
             ('uuuh', 2),
             ("that'm", 1),
             ('not', 834),
             ('with', 1179),
             ('either', 27),
             ('ciaranstrange', 3),
             ('sasspiria', 1),
             ('playstation', 101),
             ('bleh', 2),
             ('favorite', 75),
             ('video', 186),
             ('assassins', 64),
             ('creed', 130),
             ('revelations', 2),
             ('film', 16),
             ('captain', 5),
             ('america', 18),
             ('winter', 1),
             ('solider', 1),
             ('book', 37),
             ('touching', 3),
             ('spirit', 12),
             ('bear', 7),
             ('manga', 2),
             ("don't", 194),
             ('read', 53),
             ('television', 3),
             ('series', 166),
             ('smallville', 1),
             ('superhero', 2),
             ('daredevil', 1),
             ('anime', 7),
             ('hero', 24),
             ('academia', 1),
             ('congrats', 19),
             ('dallasempire', 2),
             ('2020', 199),
             ('championship', 12),
             ('win', 143),
             ('else', 53),
             ('won', 71),
             ('callofduty', 59),
             ('holy', 40),
             ('what', 386),
             ('world', 160),
             ('omg', 33),
             ('dreamcatcher', 1),
             ('x', 159),
             ('league', 153),
             ('federals', 1),
             ('cruises', 1),
             ('paybackindia', 2),
             ('50', 20),
             ('it', 1923),
             ('also', 205),
             ('received', 29),
             ('an', 420),
             ('amazon', 293),
             ('e', 47),
             ('voucher', 2),
             ('offering', 3),
             ('inr', 2),
             ('500', 16),
             ('as', 550),
             ('payback', 5),
             ('rewards', 43),
             ('if', 508),
             ('don’t', 52),
             ('come', 129),
             ('ain’t', 10),
             ('buying', 29),
             ('china', 20),
             ('closes\xa0foxconn', 1),
             ('johnson', 417),
             ('samsung', 17),
             ('factories', 4),
             ('amid', 8),
             ('virus', 18),
             ('outbreak\xa0', 1),
             ('libertarianhub', 2),
             ('01', 18),
             ('27', 5),
             ('chi…', 1),
             ('https', 318),
             ('t', 483),
             ('co', 353),
             ('cltmh7bc2m', 2),
             ('just', 887),
             ('spent', 28),
             ('hour', 39),
             ('home', 223),
             ('depot', 143),
             ('renovating', 1),
             ('expensive', 14),
             ('hell', 79),
             ('closer', 2),
             ('birthday', 34),
             ('cool', 105),
             ('exhausted', 5),
             ('from', 585),
             ('work', 176),
             ('week', 75),
             ('probably', 88),
             ('stream', 119),
             ('today', 216),
             ('stoked', 4),
             ('ok', 45),
             ('dont', 74),
             ('care', 122),
             ('charge', 11),
             ('70', 22),
             ('too', 174),
             ('toxic', 29),
             ('masculinity', 4),
             ('sent', 21),
             ('specifically', 1),
             ('searching', 7),
             ('“men’s', 2),
             ('hair', 12),
             ('again', 203),
             ('d', 66),
             ('mean', 54),
             ('midterms', 2),
             ('because', 308),
             ('it’s', 119),
             ('late', 37),
             ('tired', 29),
             ('atvi', 2),
             ('update', 127),
             ('their', 228),
             ('most', 215),
             ('popular', 8),
             ('hearthstone', 116),
             ('is', 2315),
             ('investors', 10),
             ('should', 131),
             ('satisfied', 7),
             ('amount', 16),
             ('things', 87),
             ('company', 75),
             ('doing', 94),
             ('make', 210),
             ('more', 414),
             ('every', 177),
             ('happy', 171),
             ('enthusiastic', 3),
             ('jerseyboys', 1),
             ('now', 544),
             ('represented', 1),
             ('fb', 13),
             ('welcome', 39),
             ('chucky', 1),
             ('csgo', 116),
             ('our', 238),
             ('chef', 1),
             ('offer', 19),
             ('content', 57),
             ('various', 3),
             ('such', 126),
             ('warcraft', 127),
             ('cs', 69),
             ('valorant', 28),
             ('click', 16),
             ('here', 208),
             ('channel', 33),
             ('tinyurl', 13),
             ('y5gm9h74', 1),
             ('«', 8),
             ('weapon', 15),
             ('development', 8),
             ('sunsetting', 1),
             ('systems', 9),
             ('best', 357),
             ('news', 162),
             ("i've", 164),
             ('heard', 23),
             ('long', 97),
             ('time', 409),
             ('those', 85),
             ('that', 1399),
             ('play', 469),
             ('any', 158),
             ('multi', 4),
             ('major', 42),
             ('season', 89),
             ('strategy', 6),
             ('plan', 26),
             ('involved', 10),
             ('know', 192),
             ('transformation', 1),
             ('needed', 17),
             ('can', 457),
             ('relate', 2),
             ('glorious', 2),
             ('days', 99),
             ('mtg', 4),
             ('bring', 37),
             ('versatile', 2),
             ('creative', 9),
             ('builds', 4),
             ('problems', 44),
             ('sexual', 7),
             ('assaults', 1),
             ('educational', 3),
             ('institutions', 1),
             ('pia', 1),
             ('fake', 23),
             ('licenses', 2),
             ('baloch', 1),
             ('students', 18),
             ('arrested', 4),
             ('protested', 1),
             ('against', 78),
             ('inaccessibility', 1),
             ('215k', 1),
             ('corona', 5),
             ('cases', 2),
             ('rising', 4),
             ('christian', 2),
             ('man', 154),
             ('shot', 52),
             ('had', 272),
             ('bought', 52),
             ('muslim', 4),
             ('majority', 2),
             ('steps', 8),
             ('taken', 47),
             ('pubg', 228),
             ('3', 368),
             ('these', 225),
             ('even', 306),
             ('wore', 3),
             ('tannis', 2),
             ('her', 120),
             ('handsome', 6),
             ('jack', 6),
             ('want', 190),
             ('report', 26),
             ('racist', 24),
             ('uses', 9),
             ('vile', 3),
             ('harass', 2),
             ('legends', 155),
             ("person's", 1),
             ('id', 38),
             ('gotcha', 1),
             ('uwu', 5),
             ('xd', 17),
             ('20', 113),
             ('dlss', 1),
             ('0', 69),
             ('graphics', 48),
             ('processors', 1),
             ('run', 44),
             ('4k', 12),
             ('speeds', 11),
             ('than', 209),
             ('60', 23),
             ('frames', 3),
             ('per', 17),
             ('second', 59),
             ('according', 7),
             ('nvidia', 202),
             ('pcg', 1),
             ('au', 7),
             ('death', 35),
             ('stran', 1),
             ('why', 357),
             ('two', 82),
             ('year', 174),
             ('old', 99),
             ('same', 113),
             ('youtube', 142),
             ('videos', 32),
             ('ten', 13),
             ('bored', 10),
             ('12', 52),
             ('great', 321),
             ('finished', 44),
             ('off', 146),
             ('last', 182),
             ('red', 247),
             ('dead', 274),
             ('redemption', 167),
             ('legendary', 14),
             ('animal', 12),
             ('pre', 43),
             ('epilogue', 2),
             ('good', 502),
             ('style', 10),
             ('pic', 557),
             ('twitter', 565),
             ('uyo0gbr2bd', 1),
             ('never', 201),
             ('miss', 78),
             ('follow', 42),
             ('current', 24),
             ('updates', 41),
             ('tech', 37),
             ('covid', 55),
             ('19', 64),
             ('comments', 20),
             ('etc', 17),
             ('exc', 1),
             ('playhearthstone', 46),
             ('legit', 12),
             ('disable', 7),
             ('djinn', 1),
             ('asap', 2),
             ('crony', 1),
             ('lame', 6),
             ('boring', 22),
             ('scar4playz', 1),
             ('clout', 1),
             ('yapur', 1),
             ('dunki', 1),
             ('talk', 39),
             ('chat', 22),
             ('entire', 24),
             ('laugh', 19),
             ('still', 347),
             ('w', 53),
             ('end', 63),
             ('another', 151),
             ('got', 313),
             ('siq5cg3mhn', 1),
             ("wouldn't", 12),
             ('party', 18),
             ('without', 77),
             ('slink', 1),
             ('bigovideo', 1),
             ('lww0vn', 1),
             ('8gjpbwzaly', 1),
             ('duvalmagic', 7),
             ('gearboxofficial', 14),
             ('wanted', 56),
             ('say', 170),
             ('saying', 47),
             ('huge', 54),
             ('thank', 192),
             ('worked', 30),
             ('working', 90),
             ('wheels', 2),
             ('gearbox', 6),
             ('’', 356),
             ('ve', 39),
             ('been', 366),
             ('crushing', 6),
             ('enven', 2),
             ('months', 41),
             ('knowing', 15),
             ('must', 44),
             ('real', 91),
             ('difficult', 20),
             ('biggest', 26),
             ('fifa', 226),
             ('21', 61),
             ('downgrades', 1),
             ('⏬', 1),
             ('1', 297),
             ('collab', 2),
             ('f', 29),
             ('sebfut', 1),
             ('waht', 3),
             ('store', 122),
             ("it's", 344),
             ('five', 20),
             ('kid', 20),
             ('microsoft', 292),
             ('wants', 18),
             ('backwards', 5),
             ('compatible', 15),
             ('console', 62),
             ('mobilesyrup', 2),
             ('05', 17),
             ('28', 14),
             ('mic…', 2),
             ('�', 3),
             ('switched', 8),
             ('galaxy', 10),
             ('note20', 1),
             ('ultra', 6),
             ('decision', 32),
             ('understand', 34),
             ('hudson', 1),
             ('odoi', 1),
             ('undervalued', 2),
             ('74', 1),
             ('price', 56),
             ('tag', 8),
             ('80', 11),
             ('million', 65),
             ("y'all", 56),
             ("ain't", 10),
             ('help', 145),
             ('bokchoy', 1),
             ('request', 15),
             ('forget', 18),
             ('gonna', 95),
             ('tube', 1),
             ('cook', 6),
             ('nasty', 17),
             ('kissing', 1),
             ('excellent', 22),
             ('piece', 19),
             ('music', 51),
             ('mini', 3),
             ('football', 23),
             ('african', 7),
             ('award', 10),
             ('george', 7),
             ('weah', 1),
             ('prez', 1),
             ('blakfesta', 1),
             ('zylo1021fm', 1),
             ('rt', 28),
             ('cragon', 1),
             ('myself', 40),
             ('dracula', 1),
             ('masquerade', 2),
             ('origins', 7),
             ('deus', 3),
             ('ex', 11),
             ('human', 22),
             ('revolution', 4),
             ('harry', 6),
             ('breath', 7),
             ('og', 12),
             ('leisure', 1),
             ('suit', 6),
             ('corps', 4),
             ('judge', 5),
             ('fluffbrawl', 1),
             ('killerxkween91', 1),
             ('itslexitaylor', 1),
             ('jbirdsgaming', 1),
             ('wtty', 1),
             ('gamewrexham', 1),
             ('gamedigital', 1),
             ('email', 26),
             ('stay', 36),
             ('safe', 28),
             ('thanks', 194),
             ('industry', 15),
             ('uk', 74),
             ('restart', 16),
             ('by', 390),
             ('9th', 2),
             ('gen', 48),
             ('iffy', 1),
             ('malphite', 1),
             ('shard', 2),
             ('art', 30),
             ('war', 88),
             ('monolith', 1),

In [23]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='pre')

In [24]:
print(sequences)

[[   0    0    0 ...   26   90  181]
 [   0    0    0 ...   88  149 2180]
 [   0    0    0 ...    6 1717 2182]
 ...
 [   0    0    0 ...  171  179  598]
 [   0    0    0 ...   83 2110 8758]
 [   0    0    0 ... 3521 5244 3186]]

In [25]:
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.models import Sequential
X = sequences

In [26]:
X

array([[   0,    0,    0, ...,   26,   90,  181],
       [   0,    0,    0, ...,   88,  149, 2180],
       [   0,    0,    0, ...,    6, 1717, 2182],
       ...,
       [   0,    0,    0, ...,  171,  179,  598],
       [   0,    0,    0, ...,   83, 2110, 8758],
       [   0,    0,    0, ..., 3521, 5244, 3186]],
      shape=(9853, 74), dtype=int32)

In [27]:
y = data['Sentiment'].values

In [28]:
y

array([0, 3, 1, ..., 1, 3, 2], shape=(9853,))

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [32]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(99,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [33]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='SparseCategoricalCrossentropy')

In [ ]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=128)

Epoch 1/10

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size